### ISSUE TITLE
**Accident** - Corejs polyfill are included without marking them as production dependency

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1422]
As titled. We got following error when we improt the commonjs module of `sdk-middleware-auth`

```
Error: Cannot find module 'core-js/modules/es6.regexp.replace' 
    at Object.<anonymous> (/usr/local/lib/node_modules/test-cli/node_modules/@commercetools/sdk-middleware-auth/dist/sdk-middleware-auth.cjs.js:5:1) 
```

If you look in the code you see an import of `core-js` modules.

```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

require('core-js/modules/es6.regexp.replace');
require('core-js/modules/es6.regexp.to-string');
require('core-js/modules/es6.object.to-string');

function _defineProperty(obj, key, value) {
  if (key in obj) {
    Object.defineProperty(obj, key, {
      value: value,
      enumerable: true,
      configurable: true,
      writable: true
    });
  } else {
    obj[key] = value;
  }

  return obj;
}
.......
```

The issue was introduced in **5.1.6** it works in  **5.1.5**

**Comment by StarpTech** [comment]
The issue was introduced with commit https://github.com/commercetools/nodejs/commit/3ab956edddcdaafe613002c2fec00509deef7c3b#diff-fc10a6682269c1fefc2abe05d1500b8a

I see no reason to include babel builtIns across all packages just for a one-time usage of `Promise.finally`.
This SDK requires Node.js >= 8 and doesn't need polyfills in that proportion.

**Comment by daern91** [comment]
Good point. Before reverting this, I'm wondering which node version you are running? We have this PR open already which could be released now. It doesn't use any polyfills anymore and drops support of node 8 as 12 goes into LTS. #1421

**Comment by StarpTech** [comment]
I'm using Node.js >= 10

**Comment by daern91** [comment]
Thanks for the quick reply. Ill merge and make a release right away. Sorry for the trouble.

**Comment by StarpTech** [comment]
No problem, I already reverted it to the previous versions. How can we avoid this? 
A CI should usually detect this. What went wrong?

**Comment by StarpTech** [comment]
I think due to the hoisted packages right? I'd recommend enabling https://github.com/benmosher/eslint-plugin-import rules on package level not monorepo level.

**Comment by daern91** [comment]
Yes, it should have, we will look into and add missing checks. 

For everyone else reading, if you're still on node 8, please downgrade. Otherwise, please bump it to **6.0.0**, the only breaking change is dropped support of Node < 10

**Comment by daern91** [comment]
Thanks for the link @StarpTech, Ill have a look 👍

**Comment by daern91** [comment]
Closing this one now. Feel free to reopen if anything is unclear or missing. 

Have a good weekend!

**Comment by StarpTech** [comment]
I'm a bit confused. I'd expect a patch release and an additional release to drop node.js 8.

btw: What's the support plan at commercetool? I asked it because Node.js 8 is still in LTS until Dec 31, 2019.

**Comment by daern91** [comment]
Hi again, I understand the confusion. I wanted to do a quick release to potentially unblock you and others who installed `latest`. Anyways, a patch has now also been released as version `5.1.7` as well. For the support plan question, I'd have to come back with an official answer later. 

Personally, I'd say we can keep patching any major problems, like this one, but also recommend to upgrade.

**Comment by StarpTech** [comment]
>  I wanted to do a quick release to potentially unblock you and others who installed latest.

I thank you for that but most of the people don't upgrade major versions automatically. There is a much higher chance that the next patch is installed.

> Personally, I'd say we can keep patching any major problems, like this one, but also recommend to upgrade.

:+1:
